### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by pcotret** [QDucasse/gigue#4]
- [x] Fix the CI issue. Seems to be related to two deprecated modules (`setuptools` and `distutils`). A solution is given in my fork: https://github.com/pcotret/gigue/commit/c5b5d6e4842f5f0c816c30a56a434337b5688f89

Then:
- [x] The Rocket CPU model may not have a constant name (https://github.com/QDucasse/gigue/blob/main/Makefile#L73). Maybe interesting to set a constant for it
- [x] Add prefix to Spike in the Makefile (https://github.com/QDucasse/gigue/blob/main/Makefile#L75)
**=> Fixed in https://github.com/QDucasse/gigue/commit/1a8163c33b77427f80043f1faacfe4b4bb46925b**

Fixes in the readme:
- [x] Description of the hardware setup (`rocket-chip`, v1.5 release). Is a non-modified CPU OK to run default benchmarks? Requirements for other [configurations](https://github.com/QDucasse/gigue/tree/main/benchmarks/config)?
- [x] Documentation section: `src` folder does not exist
- [x] Quick reminder of what can be done with `python -m gigue -h` (in other words, description of parameters)
- [ ] Analysis on an execution with some parameters

**Comment by QDucasse** [comment]
For the CI issue:
- A temporary fix is issued in latest commit [eea8dbd](https://github.com/QDucasse/gigue/commit/eea8dbdf354fef1733f720d6033a0610e54fcf4c#diff-fb6a686182f16eb54af3c628f38593f347f68aba31de903983023c560288d7a1) that simply reverts the treatment of warnings as errors
- `pkg_resources` should not be used anymore as it is deprecated but used in both [unicorn](https://github.com/unicorn-engine/unicorn/blob/7b8c63dfe650b5d4d2bf684526161971925e6350/bindings/python/unicorn/unicorn.py#L85) and [capstone](https://github.com/capstone-engine/capstone/blob/68e27071200cb355e03a53b5c1fbc89e7a4486a9/bindings/python/capstone/__init__.py#L343)
 > A fix I tried in local is to convert both calls to `pkg_resources` following migration recommendations proposed by [`importlib_resources`](https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename). As it is working, I will propose a PR to both repositories! Note that this issue only occurs through `pytest`

**Comment by QDucasse** [comment]
More on the CI issue here: https://github.com/unicorn-engine/unicorn/issues/1829

**Comment by pcotret** [comment]
https://github.com/QDucasse/gigue/commit/9a39b24687ddd829a5a937cb7f6c448de0ddf4c3 specifies the Rocket version needed.
